apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gankidis/eks-manifests-repo.git
    targetRevision: HEAD
    path: overlays/dev/tenant2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tenant2
  syncPolicy:
    automated: 
     prune: true
      selfHeal: true
