apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base

patches:
  - path: deployment-patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: service-patch.json
    target:
      version: v1
      kind: Service
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
