apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: httpd-container
          image: nginx:latest
          ports:
            - containerPort: 80
