apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 8
  template:
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
