apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
patches:
  - path: ingress-patch-maintenance.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
