apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: maintenance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
