apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - path: deployment-patch.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: community-web
  - path: service-patch.json
    target:
      version: v1
      kind: Service
