apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
namePrefix: tenant1-
commonLabels:
  app: tenant1-app
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: deployment-patch.json
