apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  #- ../../../hooks
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
    path: deployment-patch.json
  - target:
      group: apps
      version: v1
      kind: Service
      name: service
    path: service-patch.json
   - target:
      group: apps
      version: v1
      kind: Ingress
      name: ingress
    path: service-patch.json
  
