apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER_DEPLOYMENT_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: PLACEHOLDER_APP_LABEL
  template:
    metadata:
      labels:
        app: PLACEHOLDER_APP_LABEL
    spec:
      containers:
        - name: PLACEHOLDER_CONTAINER_NAME
          image: PLACEHOLDER_CONTAINER_IMAGE
          ports:
            - containerPort: 80
