apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: PLACEHOLDER_REPLICAS
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
        - image: PLACEHOLDER_IMAGE
          imagePullPolicy: Always
          name: app-2048
          ports:
            - containerPort: 80
