apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: PLACEHOLDER_REPLICAS
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: PLACEHOLDER_IMAGE
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 80
