apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-maintenance
  namespace: PLACEHOLDER_NAMESPACE
spec:
  replicas: 0
  selector:
    matchLabels:
      app: community-maintenance
  template:
    metadata:
      labels:
        app: community-maintenance
    spec:
      containers:
        - name: community-maintenance
          image: nginx:latest
          ports:
            - containerPort: 80
