apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: PLACEHOLDER_NAMESPACE
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  selector:
    app: maintenance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
